# Redis Helm Values for Image Processing Pipeline
# Customized for Minikube deployment

# Enable persistence
persistence:
  enabled: false

# Authentication
auth:
  enabled: true
  sentinel: false

# Service configuration
service:
  type: ClusterIP

# Resource limits
resources:
  requests:
    memory: "128Mi"
    cpu: "50m"
  limits:
    memory: "256Mi"
    cpu: "200m"

# Security context
securityContext:
  enabled: true
  runAsUser: 1001
  fsGroup: 1001

# Pod security context
podSecurityContext:
  enabled: true
  fsGroup: 1001
